### ISSUE TITLE
Is the Java invocation of PMML file exported by Nyoka the same as that of PMML file exported by sklearn?

### ISSUE THREAD

**Issue by judyXiang** [nyoka-pmml/nyoka#19]
If so, do you have a demo reference for calling the PMML file exported by Nyoka from java? Thank you.
I successfully invoked the PMML file exported by sklearn with java. But calling the PMML file exported by Nyoka with the same code will cause an error.

**Comment by judyXiang** [comment]
This is my code:    
public static void predictLrHeart(Map<String, Double> irismap,String  pathxml)throws Exception {

        PMML pmml;
     
        File file = new File(pathxml);
        InputStream inputStream = new FileInputStream(file);
        try (InputStream is = inputStream) {
            pmml = org.jpmml.model.PMMLUtil.unmarshal(is);

            ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory
                    .newInstance();
            ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory
                    .newModelEvaluator(pmml);
            Evaluator evaluator = (Evaluator) modelEvaluator;

            List<InputField> inputFields = evaluator.getInputFields();
            Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();
            for (InputField inputField : inputFields) {
                FieldName inputFieldName = inputField.getName();
                Object rawValue = irismap
                        .get(inputFieldName.getValue());
                FieldValue inputFieldValue = inputField.prepare(rawValue);
                arguments.put(inputFieldName, inputFieldValue);
            }

            Map<FieldName, ?> results = evaluator.evaluate(arguments);
            List<TargetField> targetFields = evaluator.getTargetFields();
          
            for (TargetField targetField : targetFields) {
                FieldName targetFieldName = targetField.getName();
                Object targetFieldValue = results.get(targetFieldName);
                System.out.println("target: " + targetFieldName.getValue()
                        + " value: " + targetFieldValue);
            }
        }
    }

And Error is:

Exception in thread "main" java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_4
	at org.jpmml.schema.Version.forNamespaceURI(Version.java:62)
	at org.jpmml.model.PMMLFilter.updateSource(PMMLFilter.java:121)
	at org.jpmml.model.PMMLFilter.startPrefixMapping(PMMLFilter.java:43)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startNamespaceMapping(AbstractSAXParser.java:2164)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:469)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.jpmml.model.JAXBUtil.unmarshal(JAXBUtil.java:78)
	at org.jpmml.model.JAXBUtil.unmarshalPMML(JAXBUtil.java:64)
	at org.jpmml.model.PMMLUtil.unmarshal(PMMLUtil.java:34)
	at com.pmml.demo.pmml.HoltWinters.HoltWintersPmml.predictLrHeart(HoltWintersPmml.java:45)
	at com.pmml.demo.pmml.HoltWinters.HoltWintersPmml.main(HoltWintersPmml.java:34)

**Comment by nyoka-pmml** [comment]
Hi @judyXiang. Currently, Nyoka uses PMML44 schema, so the namespace is "http://www.dmg.org/PMML-4_4". From your error, it looks like your engine does not support PMML44. Could you please check the schema version supported by your engine?

**Comment by zxw131205** [comment]
I ran into the same problem.I changed "<PMML xmlns="http://www.dmg.org/PMML-4_4" in "lightgbm.pmml" to "<PMML xmlns="http://www.dmg.org/PMML-4_3" .Succeeded.
